#!/bin/bash
if [[ ! -e ~/bin/tester ]]; then
  echo "Error: Tester is not installed. Clone https://github.com/cconklin/tester and symlink tester/bin/tester to ~/bin/"
  echo "       Ensure that you are using the 'iridium' branch of tester."
  exit 1
fi
root=`dirname $(dirname $(pwd)/$0)`
pushd $root >& /dev/null
  root=$(pwd)
popd >& /dev/null
for test_file in $(find $root/test -name "*.c")
do
  test_name="${test_file%.*}"
  clang ${test_file} -o ${test_name} >& /dev/null
  if [[ ! -e ${test_name} ]]; then
    echo '#!/bin/bash' > ${test_name}
    echo "echo 'Compile Error: $test_file'" >> ${test_name}
    echo "exit 3" >> ${test_name}
    chmod 777 ${test_name}
  fi
done
~/bin/tester $@
find $root/test -type f | grep "\." -v | xargs rm